from src.db.database import Base
from sqlalchemy import Column, BigInteger, Integer, String, Float, Date

class LicitacaoModel(Base):
    __tablename__ = 'painel_bi_info_gerais_licitacoes_dev'

    seq_dim_licitacao = Column(BigInteger, primary_key=True)
    cod_meso_regiao = Column(Integer)
    cod_micro_regiao = Column(Integer)
    cod_modalidade = Column(Integer)
    dat_abertura = Column(Date)
    dat_edital_convite = Column(Date)
    dat_publicacao_edital_do = Column(Date)
    dat_publicacao_edital_veiculo_1 = Column(Date)
    dat_publicacao_edital_veiculo_2 = Column(Date)
    dat_recebimento_doc = Column(Date)
    dsc_objeto = Column(String)
    dsc_objeto_busca = Column(String)
    funcoes = Column(String)
    ind_esfera = Column(String)
    nom_comarca = Column(String)
    nom_entidade = Column(String)
    nom_fonte_recurso = Column(String)
    nom_meso_regiao = Column(String)
    nom_micro_regiao = Column(String)
    nom_modalidade = Column(String)
    nom_reg_patrimonio_publico = Column(String)
    num_exercicio = Column(Integer)
    num_exercicio_licitacao = Column(Integer)
    num_modalidade = Column(Integer)
    num_processo_licitatorio = Column(String)
    vlr_latitude = Column(Float)
    vlr_licitacao = Column(Float)
    vlr_longitude = Column(Float)   
    ranking_irregularidades = Column(Float)
    seq_dim_entidade = Column(BigInteger)   
    qtd_populacao_total = Column(Integer)
    flag_lict_unic_com_venc = Column(Integer)
    flag_lict_unic_sem_venc = Column(Integer)
    flag_existe_licitante_nao_ativo = Column(Integer)
    flag_existe_email_em_comum = Column(Integer)
    flag_existe_tel_em_comum = Column(Integer)
    flag_lograd_nro_compl_comum = Column(Integer)
    flag_nao_socios_comum = Column(Integer)
    flag_socios_comum = Column(Integer)
    flag_possui_vencedor_frequente = Column(Integer)
    flag_possui_perdedor_frequente = Column(Integer)
    flag_licitante_cnae_incongruente = Column(Integer)
    flag_licitante_antes_atividade = Column(Integer)
    flag_licitante_restricao_ceis = Column(Integer)
    flag_licitante_servidor_publico = Column(Integer)
    flag_possui_irregularidade = Column(Integer)
    qtde_licitantes_nao_ativos = Column(Integer)
    qtde_licitantes_nao_ativos_vencedores = Column(Integer)
    qtde_emails_que_repetem = Column(Integer)
    qtde_de_cnpjs_envolvidos_emails = Column(Integer)
    qtde_tels_que_repetem = Column(Integer)
    qtde_de_cnpjs_envolvidos_tels = Column(Integer)
    qtd_lograd_nro_compl_comum = Column(Integer)
    qtde_de_cnpjs_envolvidos_endereco = Column(Integer)
    qtd_nao_socios_comum = Column(Integer)
    qtd_cnpjs_envolvidos_nao_socios_comum = Column(Integer)
    qtd_socios_comum = Column(Integer)
    qtd_cnpjs_envolvidos_socios_comum = Column(Integer)
    qtd_cnpjs_vencedores_frequentes = Column(Integer)
    qtd_cnpjs_perdedores_frequentes = Column(Integer)
    qtd_cnpjs_cnae_incongruente = Column(Integer)
    qtd_cnpjs_antes_atividade = Column(Integer)
    qtd_cnpjs_restricao_ceis = Column(Integer)
    qtd_cnpjs_socio_servidor_publico = Column(Integer)
    somatorio_de_emails_repetidos = Column(Integer)
    somatorio_de_tels_repetidos = Column(Integer)

    class Config:
        arbitrary_types_allowed = True
