from typing import Optional
from pydantic import BaseModel, Field

class Item(BaseModel):
    item_id: str = Field(example="11442433", title='Identificador do item')
    grupo: str = Field(example="gasolina_8", title="Grupo a qual o item faz parte")
    grupo_id: str = Field(example="27294", title='ID do grupo')
    dsc_unidade_medida: str = Field(example="caixa", title="Unidade de medida do objeto na licitação correspondente")
    grupo_ruido: int = Field(example=0, title="Se o grupo a qual o item faz parte é um grupo de ruído")
    item_ruido: int = Field(example=0, title="Se o item corresponde a um ruído para o grupo em que faz parte")
    original: str = Field(example="GASOLINA COMUM 05 LITROS", title='Descrição do objeto na licitação correspondente')
    licitacao: str = Field(example="354082", title='Identificador da licitaçao')
    licitacao_item: str = Field(example="10019442", title='ID do item na licitação')
    original_dsc: str = Field(example="gasolina comum 5 litros", title='Descrição padronizada do objeto na licitação correspondente')
    primeiro_termo: str = Field(example="gasolina", title='Primeiro termo da descrição do item')
    ano: int = Field(example=2015, title="Ano em que a licitação foi homologada")
    mes: int = Field(example=3, title="Mês em que a licitação foi homologada")
    qtde_item: int = Field(example=10, title='Quantidade de itens homologados')
    preco: float = Field(example=16.9, title="Valor do item licitado")
    cnpj_vencedor: str = Field(example="00874929000140", title='CPF/CNPJ do licitante vencedor')
    flag_cpf_cnpj_valido: bool = Field(example="[v]", title='Indica se CPF/CNPJ do vencedor é válido')
    nome_vencedor: str = Field(example="MED CENTER COMERCIAL LTDA", title='Nome do licitante vencedor')
    tipo_vencedor: str = Field(example="J", title='Tipo do licitante vencedor')
    orgao: str = Field(example="PREFEITURA MUNICIPAL DE ITANHANDU", title='Órgão responsável por iniciar o processo de licitação')
    tipo_orgao: str = Field(example="PREFEITURA MUNICIPAL", title='Tipo do órgão responsável por iniciar o processo de licitação')
    regiao_planejamento: str = Field(example="SUL", title='Região de planejamento em que a licitação ocorreu')
    municipio: str = Field(example="ITANHANDU", title='Município em que a licitação ocorreu')
    microrregiao: str = Field(example="SAO LOURENCO", title='Microrregião em que a licitação ocorreu')
    mesorregiao: str = Field(example="SUL/SUDOESTE DE MINAS", title='Mesorregião em que a licitação ocorreu')
    regiao_imediata: str = Field(example="SAO LOURENCO", title='Região imediata em que a licitação ocorreu')
    regiao_intermediaria: str = Field(example="POUSO ALEGRE", title='Região intermediária em que a licitação ocorreu')
    modalidade: str = Field(example="PREGAO PRESENCIAL", title='Modalidade da licitação')
    tipo_licitacao: str = Field(example="MENOR PRECO", title='Tipo da licitação')
    natureza_objeto: str = Field(example="COMPRAS E OUTROS SERVICOS", title='Natureza do objeto da licitação')
    data: str = Field(example="2015-03-02", title='Data em que a licitação foi homologada')
